
# .github/workflows/git-sync.yml 
 
on: push 
jobs: 
  git-sync: 
    runs-on: ubuntu-latest 
    steps: 
      - name: git-sync 
        uses: wei/git-sync@v3 
        with: 
          source_repo: "n14s/java-dummy" 
          source_branch: "main" 
          destination_repo: "n14s/java-dummy" 
          destination_branch: "mirror"
