# File: .github/workflows/repo-sync.yml

on:
  schedule:
  - cron:  "*/1 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://${{secrets.GITHUB_TOKEN}}@github.com/n14s/blink-break.git"
        source_branch: "main"
        destination_branch: "mirror-with-cron"
        github_token: ${{secrets.GITHUB_TOKEN}}
